### ISSUE TITLE
reading MPS slow?

### ISSUE THREAD

**Issue by leoliberti** [jmaerte/pysmps#11]
Hi, 

I'm reading a MIP instance from MIPLIB2017, set3-09.mps.gz, which is 75072 bytes when compressed, 528046 bytes when uncompressed. 

I'm using Python 3.10.6_1 on my recent MacBook Pro M1Max (Darwin localmachine 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64). 

This is not a huge instance, so I would expect pysmps to read it very fast if not instantly. In fact, it takes 
real    0m32.953s
user    0m10.456s
sys     0m24.843s
which is very puzzling. I think 10s of user time is a lot, but I'm also surprised by 24s of system time. 

Thanks for your attention
Yours,
Leo Liberti

**Comment by jmaerte** [comment]
Hi,

it‘s indeed true that the master branch of the project contains very imperformant code because of list concatenations. I have worked out some of this in numpy_free branch tho I have not checked examples for correctness there.

I will take a look into this!

**Comment by jmaerte** [comment]
As in your other issue I would like to ask you to switch to the numpy_free branch and test again. It would be really interesting to me how the other code performs for the same problem.

**Comment by leoliberti** [comment]
When I was younger I was a competent programmer, sysadmin, and netadmin, who was certainly able to run two different versions of the same software module without one influencing the other. Today, all I do is "pip install" in the reduced time I can reserve for such tasks. I don't want to install an undebugged version of numpy systemwide on my laptop. So, either you give me precise (and compact) instructions about how to carry out this test, or else I'm not going to be able to. Or perhaps you can simply download set3-09.mps.gz from MIPLIB2017 and carry out the test yourself? Sorry about this. I don't mean to sound dismissive -- I'm very grateful for caring about this issue. But I really think it would be unrealistic for me to just say "ok I'll do it".

**Comment by jmaerte** [comment]
It is not a undebugged version of numpy. It is a branch of this project which is not using numpy - hence numpy_free...

However... On my machine the execution of reading in this file takes 91ms with this branch. It is not commited to pip yet since I do not seem to find the time to debug this at the moment.

**Comment by jmaerte** [comment]
Sorry for the imperformant code in the pip branch but it was enough for my purposes back then and I thought I'd share it; I will schedule some time to debug the more performant code.

**Comment by leoliberti** [comment]
Whoops! Sorry, I had totally misunderstood your message! OK then.

**Comment by jmaerte** [comment]
Same as for the other issue: This is resolved by the latest commit. Pip will eventually be updated after a test-phase.
