### ISSUE TITLE
variable bound tag 'BV' ignored

### ISSUE THREAD

**Issue by leoliberti** [jmaerte/pysmps#12]
Hi, 

Upon reading the MIPLIB2017 instance pb-market-split8-70-4.mps.gz , I noticed that pysmps declares variables as general integers unbounded above, whereas the .MPS declares them as "BV" bounds, which means "binary variables" (check http://plato.asu.edu/cplex_mps.pdf on page 9). Does pysmps ignore this tag? Why?

Thanks
Yours
Leo Liberti

**Comment by jmaerte** [comment]
Im not sure if this feature is implemented - tho I think it should be.

Will check it and eventually add it in case its not implemented.

**Comment by jmaerte** [comment]
I had a look in the source code just now and it is already implemented in the numpy_free version of the code (which is the go-to right now). The only reason that this branch is not the master already is because it is not debugged yet.

**Comment by jmaerte** [comment]
This problem is solved by the latest commit. I will test this code more in-depth and eventually update the pip version to it.
