### ISSUE TITLE
Not loading MPS files correctly

### ISSUE THREAD

**Issue by VolodyaCO** [jmaerte/pysmps#14]
The documentation in the pypi website says that it can open `.mps` files. However, when I try it it fails because it expects a `.cor` file?

```zsh
>>> smps.load_smps("stein9inf.mps")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vladimir/micromamba/envs/zapata/lib/python3.8/site-packages/pysmps/smps_loader.py", line 462, in load_smps
    name, objective_name, row_names, col_names, col_types, types, c, A, rhs_names, rhs, bnd_names, bnd = load_mps(path + ".cor")
  File "/Users/vladimir/micromamba/envs/zapata/lib/python3.8/site-packages/pysmps/smps_loader.py", line 355, in load_mps
    with open(path, "r") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'stein9inf.mps.cor'
```

Why isn't it opening my `.mps` file?

**Comment by jmaerte** [comment]
The issue is that you use the SMPS function rather than the MPS function.

Note that the current github version is out of sync with the pip version since debugging did not happen for the newer version yet!

**Comment by VolodyaCO** [comment]
Used github's `read_mps` (v1.6) and I could parse the MPS file.

**Comment by jmaerte** [comment]
Perfect!
