### ISSUE TITLE
mps_loader: MPS.add_range - missing index

### ISSUE THREAD

**Issue by dansplain** [jmaerte/pysmps#17]
https://github.com/jmaerte/pysmps/blob/aacdfc26959a0b267b331860e1fb717d924b3a52/pysmps/mps_loader.py#L197

Hello - Thank you for making this code available, it is very helpful. I think there may be a missing `[constr]` index on L197 (referenced above), and I propse that the corrected line should read:

`self.ranges[self.curr_range][constr] = {"lower": 0, "upper": 0}`

**Comment by jmaerte** [comment]
Hello!

Thank you for the corrections - I think you are definitely right!

However - as the master branch is deprecated anyway and I am only waiting for tests of the `numpy_free` branch to be performed so I can replace the master branch by it, I think I won't perform a separate correction on the master branch.

It would be a huge help for me if you'd test the numpy_free branch for your use cases!

Best regards,
Julian

**Comment by dansplain** [comment]
Thank you so much for the prompt response! I certainly will test the numpy_free branch.

Thanks again,
Danny
