### ISSUE TITLE
Comments in SIF (MPS) files

### ISSUE THREAD

**Issue by Schedulaar** [jmaerte/pysmps#5]
Hi, thanks for your great work btw!

I used your library to parse netlib test problems
(http://www.numerical.rl.ac.uk/cute/netlib.html)
and ran into the problem, that your library doesn't ignore the comments prefixed by `*`. I don't know, whether it is common-style to have comments in MPS files, but I thought I tell you about it :).

Having comments in there, I get the following error:
```
Traceback (most recent call last):
  File "./generate-test-files-from-mps.py", line 3, in <module>
    result = loader.load_mps("80BAU3B.SIF")
  File "smps_loader.py", line 352, in load_mps
    if line[0] == "ENDATA":
IndexError: list index out of range
```

**Comment by jmaerte** [comment]
Well from what I know, there are a lot of smps files out there not really according to the paradigms... So it's hard to say, if the star operator really is reserved for comments or not. I will take a look at this in the afternoon and commit a fixed version handling comments.

**Comment by jmaerte** [comment]
Ok this is weird.. In the code it explicitly states
```
if line[0] == "ENDATA":
    break
if line[0] == "*":
    continue
```
so in case there occurs a comment stated by `*` it just takes the next line and goes on from there effectively ignoring that line.

So the code handles comments just fine; does it persist after removing the comments? How exactly are your comments formulated; do you pay attention to a space being inserted after the asterisk?

List index out of range implies that there might be no elements in this line after splitting.

Please try again with the version 1.5.5 on pypi.

**Comment by Schedulaar** [comment]
Deleting the comments fixed the problem, yeah.
An example where this occured is the problem 25FV47.SIF. The header of that file looks like this:
```
***************************
* SET UP THE INITIAL DATA *
***************************

NAME          25FV47                                                            

*   Problem:
*   ********

*   An LP, contributed by John Reid.
*   This problem is sometimes called BP or BP1.

*   Source:
*   The NETLIB collection of test problems.

*   SIF input: (already in MPS format)

*   classification LLR2-AN-1571-822
```

With version 1.5.5 it does work even with these comments in the problem!
Probably the issue was with the multiple `*` without a space inserted after it?

**Comment by jmaerte** [comment]
Ah I see. So basically starting commented lines with `*` is according to the paradigm of MPS.
The error I see here in your file is the first and third line. The star operator for commenting out is not followed by a space bar, so my algorithm does not recognize it a comment. I fixed this in the latest commit - I now discord any line that even starts with `*` rather than checking for the line operator (i.e. the first "word" of the line) being `*`.

Hopefully this fixes this issue now; please report back to me if it worked.

Thanks.

**Comment by Schedulaar** [comment]
Yep, version 1.5.5 fixed it, thanks a lot!

**Comment by jmaerte** [comment]
Glad it works. Closing.
